name: Lezetho Portfolio - Publish
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action - Checkout
        uses: actions/checkout@v4
      - name: GitHub Action - Configure Pages
        uses: actions/configure-pages@v4
      - name: Github Action - Jekyll Build Pages
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: GitHub Action - Upload Pages using Artifact
        uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: GitHub Action - Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
